### ISSUE TITLE
which browser should i use with win10?

### ISSUE THREAD

**Issue by LiaoLW** [fraunhoferhhi/omaf.js#8]
I want to play 360 tiled videos with vive pro, but there isnt any browser to support hevc decoder well.
MS edge can decode hevc but it doesnt support any VR devices, the chromium suggested in issue 5 cant load the test mpd u provided.(74.0.3729.169 (64-bit))
![192 168 1 187_1234_omaf js-master_](https://user-images.githubusercontent.com/49851668/58555628-827f0a80-824c-11e9-8bc3-4e3a0f36a62c.png)
is there any settings wrong i've made or any decoder/extension i've missed?

**Comment by podborski** [comment]
Hi @LiaoLW, thank you for pointing to this issue.

Chromium seems to have some problems with `codecs="hvc1.2.L153.B0"` looks like that specific profile is not supported (I tried to hardcode it to `codecs="hvc1.1.6.L153.B0"` which results in decoding issues as shown below. (Not surprising, though 😄)
![Capture](https://user-images.githubusercontent.com/40244254/58560544-a11ddb00-8225-11e9-8ad4-1eb02598b039.png)

Files generated with [Nokia Creator](https://github.com/nokiatech/omaf) work better on Chromium. Those have `codecs="hvc1.1.6.L183.80"`. I uploaded some content generated with Nokia tools to the same [datacloud link](https://datacloud.hhi.fraunhofer.de/nextcloud/s/38tHKMQTogibTKM) located in **Garage_nokia_erp** folder.

You can try to use those files in order to test if it works for you. However, rendering is really laggy as described in #5.

Note, that Nokia's files use `L183` which is not correct in my opinion. Because it means level 6.1 but the files are level 5.1 compliant and therefore it should be set to `L153`.

**Comment by LiaoLW** [comment]
thanks for ur help, the new test videos can play with this browser but its fps seems to be under 10, maybe due to the browser didnt decode with gpu? i've read the issue #5 but it doesnt provide solution, so do u know how to force the browser to decode with gpu or anywhere i can see the list of codec this browser support? thx for ur help again.

**Comment by podborski** [comment]
First of all, thank you, this issue helped to figure out that we probably have a small bug in our `codecs` parameter. I will check that. 

So, if I specify correct codecs parameter Chromium can decode our Video (Cubemap) and also Nokia's video (ERP) and those are decoded without any problems.
I tested decoding the videos without rendering and it is also fast enough (30 fps worked fine without any lags, 60 fps are a bit to slow to decode on Chromium, but is fast enough on macOS Safari). You can test it with `me.html` page, which I wrote to test only the video part without rendering. 
Here is a screenshot of what is actually decoded, and as you can see, there are no tiles missing as in picture above.
![Capture](https://user-images.githubusercontent.com/40244254/58704012-dbfd4b80-83aa-11e9-80fe-513e029684a3.png)

It seems to me that only rendering part makes some problems on Chromium. In case of CMP files some tiles are missing (which is really strange), and in both cases (ERP and CMP) rendering is too slow even on pause, when no video decoder is involved at all. 
I tried to analyse that and I see that `window.webkitRequestAnimationFrame` takes too long:
![Capture](https://user-images.githubusercontent.com/40244254/58704963-08ff2d80-83ae-11e9-971d-63069281ad7d.png)
Not sure yet, if WebGL stuff on Chromium is too slow or if its due to our implementation.

**Comment by podborski** [comment]
@LiaoLW, I did some comparison of Safari on macOS vs Chromium on Win 10 on the same code and on the same video with unminified three.js and here is the result:
<img width="1213" alt="safari_vs_chromium" src="https://user-images.githubusercontent.com/40244254/58707292-c2f99800-83b4-11e9-87d0-972cd675a85a.png">

`gl.texImage2D.apply( gl, arguments );` from three.js::texImage2D() takes approx. 58x longer on Chromium than on Safari. And this is why it is so slow. Not sure if Chromium developers (or three.js developers) are aware of this.

This is so annoying, there is always something either not supported or not working fast enough. 
Unfortunately I don't see a quick solution for Windows right now. That `edgebrowser` branch which we created is also only experimental, since Edge also has some issues with low delay video track switching.

**Comment by LiaoLW** [comment]
thanks, it seems that i must wait for the developers to solve that problem.i'll try on linux instead. thanks again.

**Comment by LiaoLW** [comment]
@podborski ,unfortunately, linux has the same problem with win10, it doesnt support hevc decode with hardware, so we can say that only Mac OS support it absolutely. 
in addition,i want to ask how to add the "enter VR mode" to select the output device, should i modify the code in Render Engine?

**Comment by JWSon** [comment]
Hi @LiaoLW,
Currently the player shows the content as one direction of camera in the cube or sphere.
If you want to separate the scene for stereo mode, you can modify the render() functions using [StereoMode.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/StereoEffect.js).
Here is [the example](https://threejs.org/examples/webgl_effects_stereo.html) :)

**Comment by podborski** [comment]
Similar issue (where not all tiles are rendered) seems to appear on older macbooks running Safari such as 2014 Mac mini.
